"""Decide which files to scan: source extensions, excluded dirs, .gitignore, tests, generated code."""

import os
import re
import subprocess
from pathlib import Path

DEFAULT_EXCLUDES = {
    ".git",
    ".hg",
    ".svn",
    "node_modules",
    "bower_components",
    "vendor",
    "dist",
    "build",
    "out",
    ".next",
    ".nuxt",
    ".svelte-kit",
    ".output",
    "storybook-static",
    "coverage",
    "__pycache__",
    ".venv",
    "venv",
    ".tox",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".cache",
    "site-packages",
    "target",
    ".turbo",
    ".gradle",
    "Pods",
}

SOURCE_EXTENSIONS = {
    ".py",
    ".js",
    ".jsx",
    ".ts",
    ".tsx",
    ".mjs",
    ".cjs",
    ".java",
    ".go",
    ".rb",
    ".php",
    ".cs",
    ".cpp",
    ".cc",
    ".c",
    ".h",
    ".hpp",
    ".swift",
    ".rs",
    ".kt",
    ".kts",
    ".scala",
    ".lua",
    ".zig",
    ".ex",
    ".exs",
    ".erl",
    ".hrl",
    ".dart",
    ".r",
    ".R",
    ".jl",
    ".ml",
    ".mli",
    ".clj",
    ".cljs",
    ".el",
    ".vim",
}

# Tests rarely hold production bottlenecks, yet they were ~30% of findings on real repos.
TEST_PATH_RE = re.compile(
    r"(^|/)(tests?|__tests__|__mocks__|specs?|e2e|testing)/|(^|/)(test_[^/]*|conftest\.py)$|[._-](test|tests|spec)\.[A-Za-z]+$"
)
# Tool conventions only: `@generated`, Go's "Code generated ... DO NOT EDIT.", .NET's <auto-generated>.
# Plain prose like "do not edit the order below" must not hide a hand-written file.
GENERATED_MARKER_RE = re.compile(r"@generated\b|^\W*Code generated .* DO NOT EDIT|<auto-generated")
GENERATED_HEADER_LINES = 5
MINIFIED_LINE_LENGTH = 1000
# Minified bundles are mostly long lines; one long prompt or data line in a source file isn't.
MINIFIED_LONG_LINE_SHARE = 0.5


def git(root: Path, *args: str) -> list[str]:
    # surrogateescape keeps non-UTF-8 file names (possible on Linux) from crashing the decode.
    output = subprocess.run(["git", *args], cwd=root, capture_output=True, text=True, errors="surrogateescape", check=True).stdout
    return [name for name in output.split("\0" if "-z" in args else "\n") if name]


def list_source_files(root: Path, excludes: set[str]) -> list[Path]:
    """Files git would track (so build output listed in .gitignore is skipped); a plain walk outside git,
    or when `root` itself is ignored by git (scanning a build directory on purpose)."""
    try:
        names = git(root, "ls-files", "-z", "--cached", "--others", "--exclude-standard")
    except (subprocess.CalledProcessError, FileNotFoundError):
        return walk_source_files(root, excludes)
    return select_sources(root, (root / name for name in names), excludes) or walk_source_files(root, excludes)


def changed_source_files(root: Path, base: str, excludes: set[str]) -> list[Path]:
    """Files changed since the merge-base with `base`, including uncommitted and untracked ones."""
    top = Path(git(root, "rev-parse", "--show-toplevel")[0]).resolve()
    merge_base = git(root, "merge-base", base, "HEAD")[0]
    names = git(root, "diff", "-z", "--name-only", "--diff-filter=d", merge_base)
    names += git(root, "ls-files", "-z", "--others", "--exclude-standard", "--full-name")
    return select_sources(root, (top / name for name in names), excludes)


def walk_source_files(root: Path, excludes: set[str]) -> list[Path]:
    paths = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(d for d in dirnames if d not in excludes)
        paths += [Path(dirpath) / name for name in sorted(filenames) if Path(name).suffix in SOURCE_EXTENSIONS]
    return paths


def select_sources(root: Path, paths, excludes: set[str]) -> list[Path]:
    """Source files under `root` outside excluded dirs. Paths come from git, already absolute and normalized."""
    selected = set()
    for path in paths:
        if path.suffix not in SOURCE_EXTENSIONS or root not in path.parents:
            continue
        if not excludes & set(path.relative_to(root).parts) and path.is_file():
            selected.add(path)
    return sorted(selected)


def is_test_path(relpath: str) -> bool:
    return bool(TEST_PATH_RE.search(relpath))


def is_generated(path: Path, lines: list[str]) -> bool:
    if ".min." in path.name or ".bundle." in path.name:
        return True
    if any(GENERATED_MARKER_RE.search(line) for line in lines[:GENERATED_HEADER_LINES]):
        return True
    code_lines = [line for line in lines if line.strip()]
    long_lines = sum(len(line) > MINIFIED_LINE_LENGTH for line in code_lines)
    return bool(code_lines) and long_lines / len(code_lines) >= MINIFIED_LONG_LINE_SHARE


def read_text(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return path.read_text(encoding="latin-1")
    except OSError:
        return None
